"""Cấu hình tĩnh cho bộ so khớp CV-JD.

File này KHÔNG chứa logic, chỉ chứa dữ liệu tĩnh:
- Trọng số (weights) và hệ số alpha của từng section.
- Bản đồ tiêu đề (heading) để nhận diện các mục trong CV/JD.
- Các danh sách từ khóa: ngôn ngữ lập trình, kỹ năng, chứng chỉ...

Khi bảo vệ đồ án, mục hay bị hỏi là DEFAULT_WEIGHTS và DEFAULT_ALPHA_MAP:
đây là nơi quyết định "section nào quan trọng bao nhiêu" khi tính điểm.
"""

import os

BASE_DIR = os.path.dirname(__file__)
ALIAS_PATH = os.path.join(BASE_DIR, "skill_aliases.json")

# Hệ số pha trộn giữa embedding và TF-IDF cho từng section (alpha càng cao càng thiên về ngữ nghĩa).
DEFAULT_ALPHA_MAP = {
    "experience": 0.75,
    "technical_skills": 0.30,
    "programming_languages": 0.10,
    "responsibilities": 0.80,
    "projects": 0.80,
    "education": 0.40,
    "certificates": 0.20,
    "natural_languages": 0.10,
    "soft_skills": 0.75,
}

# Trọng số của từng section khi cộng dồn thành điểm tổng (tổng ~= 1.0).
DEFAULT_WEIGHTS = {
    "experience": 0.25,
    "technical_skills": 0.25,
    "programming_languages": 0.15,
    "responsibilities": 0.10,
    "projects": 0.10,
    "education": 0.05,
    "certificates": 0.04,
    "natural_languages": 0.04,
    "soft_skills": 0.02,
}

# Nhãn hiển thị của từng section (dùng cho phần giải thích/kết quả).
SECTION_LABELS = {
    "experience": "Experience",
    "technical_skills": "Technical Skills",
    "programming_languages": "Programming Languages",
    "responsibilities": "Responsibilities",
    "projects": "Projects",
    "education": "Education",
    "certificates": "Certificates",
    "natural_languages": "Natural Languages",
    "soft_skills": "Soft Skills",
}

# Tập tất cả khóa section nội bộ hợp lệ (gồm cả các mục phụ như requirements, summary...).
INTERNAL_SECTION_KEYS = set(SECTION_LABELS) | {"requirements", "preferred", "summary", "ignored"}

# Bản đồ ánh xạ cụm tiêu đề (viết thường) -> section chuẩn.
# Đây là "từ điển" để nhận diện mục nào là kinh nghiệm, kỹ năng, yêu cầu...
HEADING_PHRASE_MAP = {
    "required qualifications": "requirements",
    "minimum qualifications": "requirements",
    "basic qualifications": "requirements",
    "mandatory qualifications": "requirements",
    "essential qualifications": "requirements",
    "required skills": "requirements",
    "required skill": "requirements",
    "required experience": "requirements",
    "required experience years": "experience",
    "experience years": "experience",
    "required competencies": "requirements",
    "minimum requirements": "requirements",
    "minimum skills": "requirements",
    "must have": "requirements",
    "must-have skills": "requirements",
    "must have skills": "requirements",
    "what you need": "requirements",
    "what we require": "requirements",
    "what we're looking for": "requirements",
    "what we are looking for": "requirements",
    "ideal candidate": "requirements",
    "ideal candidate profile": "requirements",
    "candidate requirements": "requirements",
    "position requirements": "requirements",
    "job requirements": "requirements",
    "role requirements": "requirements",
    "qualifications": "requirements",
    "requirements": "requirements",
    "preferred qualifications": "preferred",
    "preferred skill": "preferred",
    "nice to have": "preferred",
    "nice-to-have": "preferred",
    "nice-to-have skills": "preferred",
    "nice to have skills": "preferred",
    "bonus qualifications": "preferred",
    "bonus points": "preferred",
    "desired qualifications": "preferred",
    "desired skills": "preferred",
    "desired experience": "preferred",
    "preferred skills": "preferred",
    "preferred experience": "preferred",
    "additional qualifications": "preferred",
    "additional skills": "preferred",
    "would be a plus": "preferred",
    "good to have": "preferred",
    "good-to-have": "preferred",
    "optional skills": "preferred",
    "what you will do": "responsibilities",
    "what you'll do": "responsibilities",
    "responsibilities": "responsibilities",
    "your responsibilities": "responsibilities",
    "key responsibilities": "responsibilities",
    "core responsibilities": "responsibilities",
    "role responsibilities": "responsibilities",
    "job responsibilities": "responsibilities",
    "the role": "responsibilities",
    "about the role": "responsibilities",
    "role overview": "responsibilities",
    "role description": "responsibilities",
    "job description": "responsibilities",
    "position overview": "responsibilities",
    "about the job": "responsibilities",
    "in this role": "responsibilities",
    "day to day": "responsibilities",
    "day-to-day": "responsibilities",
    "duties": "responsibilities",
    "key duties": "responsibilities",
    "tasks": "responsibilities",
    "core strengths": "technical_skills",
    "tech stack": "technical_skills",
    "technical skills": "technical_skills",
    "technical expertise": "technical_skills",
    "technical competencies": "technical_skills",
    "technical requirements": "technical_skills",
    "technology stack": "technical_skills",
    "technologies": "technical_skills",
    "tools and technologies": "technical_skills",
    "tools & technologies": "technical_skills",
    "tools and frameworks": "technical_skills",
    "skills and technologies": "technical_skills",
    "skills & technologies": "technical_skills",
    "key skills": "technical_skills",
    "core skills": "technical_skills",
    "skills": "technical_skills",
    "expertise": "technical_skills",
    "competencies": "technical_skills",
    "stack": "technical_skills",
    "profile snapshot": "summary",
    "experience summary": "experience",
    "profile": "summary",
    "professional profile": "summary",
    "professional summary": "summary",
    "career summary": "summary",
    "summary": "summary",
    "about me": "summary",
    "career overview": "summary",
    "candidate summary": "summary",
    "candidate profile": "summary",
    "background": "summary",
    "professional background": "summary",
    "objective": "summary",
    "snapshot": "summary",
    "experience": "experience",
    "work experience": "experience",
    "professional experience": "experience",
    "employment history": "experience",
    "work history": "experience",
    "career history": "experience",
    "relevant experience": "experience",
    "selected projects and skills": "projects",
    "selected projects": "projects",
    "projects": "projects",
    "key projects": "projects",
    "notable projects": "projects",
    "featured projects": "projects",
    "personal projects": "projects",
    "open source projects": "projects",
    "open-source projects": "projects",
    "portfolio": "projects",
    "project highlights": "projects",
    "education": "education",
    "education requirement": "education",
    "education requirements": "education",
    "educational background": "education",
    "academic background": "education",
    "academic qualifications": "education",
    "degrees": "education",
    "university": "education",
    "college": "education",
    "certifications": "certificates",
    "certificates": "certificates",
    "professional certifications": "certificates",
    "professional certificates": "certificates",
    "licenses and certifications": "certificates",
    "training": "certificates",
    "courses": "certificates",
    "languages": "natural_languages",
    "language": "natural_languages",
    "language requirement": "natural_languages",
    "language requirements": "natural_languages",
    "spoken languages": "natural_languages",
    "language skills": "natural_languages",
    "foreign languages": "natural_languages",
    "soft skills": "soft_skills",
    "interpersonal skills": "soft_skills",
    "communication skills": "soft_skills",
    "leadership skills": "soft_skills",
    "personal attributes": "soft_skills",
    "what you bring": "soft_skills",
    "about us": "ignored",
    "about the company": "ignored",
    "about the team": "ignored",
    "who we are": "ignored",
    "benefits": "ignored",
    "benefits and work location": "ignored",
    "work location": "ignored",
    "location": "ignored",
    "level": "ignored",
    "keywords": "ignored",
    "role category": "ignored",
}

# Từ đồng nghĩa của tiêu đề section (hỗ trợ cả tiếng Việt), dùng khi HEADING_PHRASE_MAP không khớp.
SECTION_SYNONYMS = {
    "summary": ["summary", "objective", "profile", "professional summary", "tóm tắt", "mục tiêu"],
    "technical_skills": ["skills", "skill", "technical skill", "technical skills", "competencies", "technologies", "stack", "tools"],
    "experience": ["experience", "work experience", "work history", "employment", "professional", "kinh nghiệm", "quá trình làm việc"],
    "projects": ["project", "projects", "portfolio", "highlights", "personal projects", "dự án"],
    "education": ["education", "degree", "university", "school", "academic", "học vấn", "trình độ học vấn"],
    "natural_languages": ["language", "languages", "foreign languages", "ngôn ngữ", "ngoại ngữ"],
    "certificates": ["certificate", "certification", "certificates", "chứng chỉ"],
    "soft_skills": ["soft skill", "communication", "teamwork", "problem solving", "collaboration", "kỹ năng mềm"],
    "responsibilities": ["responsibilities", "responsibility", "tasks", "duties", "what you will do", "job description"],
    "requirements": ["requirements", "required", "must have", "qualification", "qualifications"],
}

# Các section chỉ chấp nhận so khớp CHÍNH XÁC (không dùng ngữ nghĩa lỏng lẻo).
STRICT_SECTIONS = {
    "technical_skills",
    "programming_languages",
    "certificates",
    "natural_languages",
}

# Danh sách ngôn ngữ lập trình được nhận diện.
PROGRAMMING_LANGUAGES = {
    "python",
    "javascript",
    "typescript",
    "java",
    "c++",
    "c#",
    "go",
    "golang",
    "rust",
    "php",
    "ruby",
    "kotlin",
    "swift",
    "sql",
}

# Danh sách ngôn ngữ tự nhiên (ngoại ngữ) được nhận diện.
NATURAL_LANGUAGES = {
    "english",
    "vietnamese",
    "french",
    "german",
    "spanish",
    "japanese",
    "korean",
    "chinese",
}

# Gợi ý kỹ năng/công nghệ để nhận diện trong phần technical skills.
SKILL_HINTS = {
    "fastapi",
    "django",
    "flask",
    "react",
    "next.js",
    "nextjs",
    "node.js",
    "nodejs",
    "express",
    "postgresql",
    "postgres",
    "mysql",
    "mongodb",
    "redis",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "linux",
    "git",
    "rest api",
    "rest",
    "spring",
    "spring security",
    "jpa",
    "hibernate",
    "websquare",
    "rdbms",
    "devops",
    "github actions",
    "jenkins",
    "project management",
    "testing",
    "system design",
    "performance optimization",
    "graphql",
    "machine learning",
    "artificial intelligence",
}

# Gợi ý các loại chứng chỉ.
CERTIFICATE_HINTS = {
    "aws certified",
    "azure certified",
    "google cloud certified",
    "ielts",
    "toeic",
    "pmp",
    "scrum",
    "certificate",
    "certification",
}

# Các kỹ năng được coi là tương đương/tương thích khi so khớp (vd JavaScript ~ TypeScript).
COMPATIBLE_SKILLS = {
    "javascript": {"typescript"},
    "rest": {"rest api"},
    "rest api": {"rest"},
}
